---
#  TODO: move this into release workflow
on:
    push:
        branches:
            - misc/pyinstaller

jobs:

    build-executables:

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]

        steps:

            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2

            - name: Install pyinstaller
              run: python -m pip install pyinstaller==4.7

            - name: Upload distribution artifact
              uses: actions/upload-artifact@v2
              with:
                  name: executable-${{ matrix.os }}
                  path: dist/
