---
name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    FORCE_COLOR: 1

jobs:

    test-package:

        runs-on: ${{ matrix.os }}
        timeout-minutes: 15

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '3.15']
                os: [ubuntu-latest]
                default-image:
                    - ''   # use the application default
                include:
                    - python-version: '3.14'
                      os: macos-latest
                      default-image: ''
                    - python-version: '3.14'
                      os: windows-latest
                      default-image: ''

        steps:

            - uses: actions/checkout@v7

            - uses: astral-sh/setup-uv@v10.2.0
              with:
                  python-version: ${{ matrix.python-version }}
                  activate-environment: true

            - name: Install package
              run: uv pip install -e .[tests]

            - name: Run tests
              run: |
                  pytest -sv --slow --default-image=${{ matrix.default-image }}
                  coverage xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  flags: py-${{ matrix.python-version }}

    test-installation-with-uv:

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '3.15']

        steps:

            - uses: actions/checkout@v7

            - uses: astral-sh/setup-uv@v10.2.0
              with:
                  python-version: ${{ matrix.python-version }}
                  activate-environment: true

            - name: Install with `uv tool`
              run: uv tool install ${{ github.workspace }}

            - name: Run smoke tests
              run: aiidalab-launch version
