---
name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    test-package:

        runs-on: ubuntu-latest
        timeout-minutes: 15

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
                default-image:
                    - ''  # use the application default
                    - aiidalab/aiidalab-docker-stack:latest  # This is the old stack

        steps:

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: true

            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package
              run: |
                  which python
                  python -m pip install -e .[tests]
                  python -m pip freeze

            - name: Run tests
              run: |
                  pytest -svv --slow --default-image=${{ matrix.default-image }}
                  coverage xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  flags: py-${{ matrix.python-version }}

    test-installation-with-pipx:

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

        steps:

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: true

            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install with pipx
              run: |
                  python -m pip install pipx
                  pipx install ${{ github.workspace }}

            - name: Run smoke tests
              run: |
                  aiidalab-launch version
