---
name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    FORCE_COLOR: 1

jobs:

    test-package:

        runs-on: ubuntu-latest
        timeout-minutes: 15

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
                default-image:
                    - ''   # use the application default
                include:
                    - default-image: aiidalab/aiidalab-docker-stack:latest   # This is the old stack
                    - python-version: '3.8'

        steps:

            - uses: actions/checkout@v7

            - uses: astral-sh/setup-uv@v10.2.0
              with:
                  python-version: ${{ matrix.python-version }}
                  activate-environment: true

            - name: Install package
              run: uv pip install -e .[tests]

            - name: Run tests
              run: |
                  pytest -sv --slow --default-image=${{ matrix.default-image }}
                  coverage xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  flags: py-${{ matrix.python-version }}

    test-installation-with-uv:

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

        steps:

            - uses: actions/checkout@v7

            - uses: astral-sh/setup-uv@v10.2.0
              with:
                  python-version: ${{ matrix.python-version }}
                  activate-environment: true

            - name: Install with `uv tool`
              run: uv tool install ${{ github.workspace }}

            - name: Run smoke tests
              run: aiidalab-launch version
