---
name: continuous-integration

on: [push, pull_request]

jobs:

    pre-commit:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
            - uses: pre-commit/action@v2.0.0

    test-package:

        needs: [pre-commit]

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10']

        steps:

            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  submodules: true

            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package
              run: |
                  which python
                  python -m pip install -e .[tests]
                  python -m pip freeze

            - name: Run tests
              run: |
                  pytest --cov=aiidalab_launch -v --slow
                  coverage json

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2

    test-installation-with-pipx:

        needs: [pre-commit]

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10']

        steps:

            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  submodules: true

            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install with pipx
              run: |
                  which python
                  python -m pip install pipx
                  pipx install ${{ github.workspace }}

            - name: Run smoke tests
              run: |
                  aiidalab-launch version
